version: '3.9'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  rabbitmqEnabledPlugin:
    image: heidiks/rabbitmq-delayed-message-exchange:latest
    container_name: test_rabbitmq_with_plugin
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
  # go_event_service:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: go_event_service
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - my_network

# networks:
#   network1