version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=s3cr3t
      - POSTGRES_USER=postgres_user
      - POSTGRES_DB=postgres_db
    networks:
      - my_network

  # go_event_service:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: go_event_service
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - my_network

networks:
  my_network:
    driver: bridge